export const OffersData = [
        {
            backgroundImgUrl: "Images/OffersImg/1.avif",
            logoUrl: "Images/OffersImg/sbi.avif",
            description: "Get 1 Free movie ticket upto INR 250 every month with Reliance SBI Card PRIME",
            cardType: "creditCard",
            title: "Reliance SBI Card PRIME",
            date: "31 mar 2026 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/2.avif",
            logoUrl: "Images/OffersImg/sbi.avif",
            description: "Get 2 free movie tickets or INR 500 off whichever is less with SBI Signature/Elite credit cards",
            cardType: "creditCard",
            title: "SBI Signature/Elite credit card offer",
            date: "31 mar 2026 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/3.avif",
            logoUrl: "Images/OffersImg/rbl.avif",
            description: "RBL Bank Monthly Offer",
            cardType: "creditCard",
            title: "RBL Bank Popcorn, Fun+, Movies & More and Blockbuster card monthly offer",
            date: "31 oct 2024 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/3.avif",
            logoUrl: "Images/OffersImg/rbl.avif",
            description: "RBL Bank Welcome Offer",
            cardType: "creditCard",
            title: "RBL Bank Popcorn, Fun+, Movies & More and Blockbuster card welcome offer",
            date: "31 oct 2024 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/4.avif",
            logoUrl: "Images/OffersImg/rbl.avif",
            description: "Buy one get one free movie ticket up to INR 200.",
            cardType: "creditCard",
            title: "RBL Bank YOUnique Credit Card Offer",
            date: "31 oct 2024 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/5.avif",
            logoUrl: "Images/OffersImg/right.avif",
            description: "Buy 1 Get 1 free movie ticket with YES Bank MARQUEE Credit Card*.",
            cardType: "creditCard",
            title: "YES Bank MARQUEE Credit Card Offer",
            date: "31 oct 2024 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/6.avif",
            logoUrl: "Images/OffersImg/right.avif",
            description: "Buy 1 get 1 movie ticket free + 50% off on non movie tickets with Yes Private Credit Card",
            cardType: "creditCard",
            title: "Yes Private Credit Card Offer",
            date: "31 dec 2025 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/6.avif",
            logoUrl: "Images/OffersImg/right.avif",
            description: "Buy 1 get 1 movie ticket free + 50% off on non movie tickets with Yes Private Credit Card",
            cardType: "debitCard",
            title: "Yes Private Credit Card Offer",
            date: "31 dec 2025 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/6.avif",
            logoUrl: "Images/OffersImg/right.avif",
            description: "Buy 1 get 1 movie ticket free + 50% off on non movie tickets with Yes Private Credit Card",
            cardType: "debitCard",
            title: "Yes Private Credit Card Offer",
            date: "31 dec 2025 23:59",
        },
        {
            backgroundImgUrl: "Images/OffersImg/6.avif",
            logoUrl: "Images/OffersImg/right.avif",
            description: "Buy 1 get 1 movie ticket free + 50% off on non movie tickets with Yes Private Credit Card",
            cardType: "wallet",
            title: "Yes Private Credit Card Offer",
            date: "31 dec 2025 23:59",
        },
]


